version: '3'
services:
  db:
    image: postgres:latest
    volumes: 
      - "dbdata:/var/lib/postgresql/data"
      - "./db:/docker-entrypoint-initdb.d/:ro"
    environment: 
      - POSTGRES_DB=postgresTest
      - POSTGRES_USER=testuser
      - POSTGRES_PASSWORD=testpass
    ports:
      - "127.0.0.1:5000:5432"
volumes:
  dbdata:
